<HTML>
<HEAD>
<TITLE>전자정부 프레임워크</TITLE>
</HEAD>

<FRAMESET COLS="25%,75%">
<FRAME SRC="EgovStrCnvrMenu.jsp" NAME="EgovComUtl" MARGINWIDTH="15" MARGINHEIGHT="65" SCROLLING="yes">
<FRAME SRC="#"  NAME="EgovComUtlFcc" MARGINWIDTH="20" MARGINHEIGHT="65" SCROLLING="no" NOREZINE>

</FRAMESET>
</HTML>